#!/usr/bin/env python3
"""
Waldorf Column Verification Test Script

This script generates test .map files to verify the correct column mapping
for Waldorf Quantum/Iridium sample maps based on hardware testing results.

The goal is to fix the current incorrect column mappings in export_waldorf_sample_map.py
"""

import os
import math
from pathlib import Path

def db_to_linear(db_value):
    """Convert decibel value to linear multiplier."""
    return math.pow(10, db_value / 20.0)

def linear_to_db(linear_value):
    """Convert linear multiplier to decibel value."""
    if linear_value <= 0:
        return -60.0  # Minimum dB
    return 20.0 * math.log10(linear_value)

def create_verification_tests():
    """Create test files to verify column mappings against hardware."""
    
    output_dir = Path("output/waldorf_verification_tests")
    output_dir.mkdir(exist_ok=True)
    
    # Base template for all tests
    base_template = {
        'sample_path': '"2:samples/test_sample.wav"',
        'pitch': 60.0,                      # Column 2: Root pitch
        'from_note': 60,                    # Column 3: Key range low
        'to_note': 60,                      # Column 4: Key range high
        'gain_db': 0.0,                     # Column 5: Gain in dB (FIXED)
        'from_velo': 1,                     # Column 6: Velocity low
        'to_velo': 127,                     # Column 7: Velocity high
        'mystery_field': 0.5,               # Column 8: Unknown/Pan/Volume?
        'sample_start': 0.0,                # Column 9: Sample start (normalized)
        'sample_end': 1.0,                  # Column 10: Sample end (normalized)
        'loop_mode': 0,                     # Column 11: Loop mode (0=off, 1=forward, 2=ping-pong)
        'loop_start': 0.0,                  # Column 12: Loop start (normalized)
        'loop_end': 1.0,                    # Column 13: Loop end (normalized)
        'direction': 0,                     # Column 14: Direction (0=forward, 1=reverse)
        'xfade': 0.0,                       # Column 15: Crossfade amount
        'track_pitch': 1                    # Column 16: Track pitch (0=no, 1=yes)
    }
    
    tests = [
        # Test Column 5: Gain in dB (currently WRONG - we put tune here)
        {
            'name': 'verify_col05_gain_db',
            'description': 'Test column 5 as gain in dB (-12, 0, +6 dB)',
            'variations': [
                {'gain_db': -12.0, 'note': 60},  # -12dB = 0.251189 linear
                {'gain_db': 0.0, 'note': 61},    # 0dB = 1.0 linear
                {'gain_db': 6.0, 'note': 62}     # +6dB = 1.995262 linear
            ]
        },
        
        # Test Column 8: Mystery field (currently we put volume here)
        {
            'name': 'verify_col08_mystery',
            'description': 'Test column 8 mystery field (0.0, 0.5, 1.0)',
            'variations': [
                {'mystery_field': 0.0, 'note': 60},
                {'mystery_field': 0.5, 'note': 61},
                {'mystery_field': 1.0, 'note': 62}
            ]
        },
        
        # Test Column 13: Loop End (verify if normalized or sample counts)
        {
            'name': 'verify_col13_loop_end',
            'description': 'Test column 13 loop end values',
            'variations': [
                {'loop_end': 0.25, 'loop_mode': 1, 'note': 60},   # 25% through sample
                {'loop_end': 0.5, 'loop_mode': 1, 'note': 61},    # 50% through sample
                {'loop_end': 1.0, 'loop_mode': 1, 'note': 62}     # End of sample
            ]
        },
        
        # Test Column 16: Track Pitch verification
        {
            'name': 'verify_col16_track_pitch',
            'description': 'Test column 16 track pitch on/off',
            'variations': [
                {'track_pitch': 0, 'note': 60, 'pitch': 60.0},  # No key tracking
                {'track_pitch': 1, 'note': 61, 'pitch': 61.0},  # Key tracking on
                {'track_pitch': 1, 'note': 62, 'pitch': 62.0}   # Key tracking on
            ]
        }
    ]
    
    # Generate test files
    for test in tests:
        filename = f"{test['name']}.map"
        filepath = output_dir / filename
        
        print(f"Creating {filename}...")
        
        with open(filepath, 'w', encoding='utf-8') as f:
            # Write header comment
            f.write(f"// {test['description']}\\n")
            f.write(f"// Generated by test_waldorf_column_verification.py\\n\\n")
            
            for var in test['variations']:
                # Create line with test variation
                values = base_template.copy()
                values.update(var)
                
                # Convert gain from dB to linear for the file
                if 'gain_db' in var:
                    gain_linear = db_to_linear(var['gain_db'])
                    values['gain_linear'] = gain_linear
                else:
                    values['gain_linear'] = db_to_linear(values['gain_db'])
                
                # Update note mappings
                note = var.get('note', 60)
                values['from_note'] = note
                values['to_note'] = note
                values['pitch'] = var.get('pitch', note)
                
                # Format the line (16 tab-separated columns)
                line = "\\t".join([
                    values['sample_path'],                          # Column 1
                    f"{values['pitch']:.8f}",                       # Column 2
                    str(values['from_note']),                       # Column 3
                    str(values['to_note']),                         # Column 4
                    f"{values['gain_linear']:.8f}",                 # Column 5: GAIN (not tune!)
                    str(values['from_velo']),                       # Column 6
                    str(values['to_velo']),                         # Column 7
                    f"{values['mystery_field']:.8f}",               # Column 8: Mystery field
                    f"{values['sample_start']:.8f}",                # Column 9
                    f"{values['sample_end']:.8f}",                  # Column 10
                    str(values['loop_mode']),                       # Column 11
                    f"{values['loop_start']:.8f}",                  # Column 12
                    f"{values['loop_end']:.8f}",                    # Column 13
                    str(values['direction']),                       # Column 14
                    f"{values['xfade']:.8f}",                       # Column 15
                    str(values['track_pitch'])                      # Column 16
                ])
                
                f.write(line + "\\n")
    
    # Create README
    readme_path = output_dir / "README.md"
    with open(readme_path, 'w', encoding='utf-8') as f:
        f.write("""# Waldorf Column Verification Tests

These test files are generated to verify the correct column mapping for Waldorf sample maps.

## Key Issues Being Tested:

1. **Column 5**: Should be GAIN in dB (linear multiplier), not tune in cents
2. **Column 8**: Mystery field - currently unknown what this controls
3. **Column 13**: Loop end position - verify if normalized (0.0-1.0) or sample counts
4. **Column 16**: Track pitch on/off verification

## Testing Process:

1. Copy a test sample to `2:samples/test_sample.wav` on your Quantum/Iridium
2. Load each .map file
3. Play the different keys (C4, C#4, D4) and note the differences
4. Document what changes between the samples

## Expected Results:

- **verify_col05_gain_db.map**: Volume should change (-12dB, 0dB, +6dB)
- **verify_col08_mystery.map**: Unknown parameter should change
- **verify_col13_loop_end.map**: Loop end points should change
- **verify_col16_track_pitch.map**: Key tracking behavior should change

## Current Code Issues:

Our current export_waldorf_sample_map.py has these problems:
- Column 5: We put `tune` (cents) instead of `gain` (linear from dB)
- Column 8: We put `volume` but unclear if this is correct
- Need to verify all other columns match hardware behavior

---
Generated: {os.path.basename(__file__)}
""")

    print(f"\\nGenerated verification test files in: {output_dir}")
    print("\\nNext steps:")
    print("1. Copy test files to Quantum/Iridium")
    print("2. Test each file and document results")
    print("3. Update export_waldorf_sample_map.py with correct mappings")


if __name__ == "__main__":
    create_verification_tests()